version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://server:5000

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
