version: '3.8'

services:
  rest-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - rest-network

  rest-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - rest-network

networks:
  rest-network:
    driver: bridge
